# Generated by Django 3.1.1 on 2020-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default-product.jpg', upload_to='profile_pics'),
        ),
    ]
