# Generated by Django 3.1.1 on 2020-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop.ProductCategory'),
        ),
    ]
