# Generated by Django 3.1.1 on 2020-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default-product.jpg', upload_to='product_pictures'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='author_name',
            field=models.CharField(max_length=30),
        ),
    ]
