# Generated by Django 3.1.1 on 2020-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200902_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_score',
            field=models.IntegerField(default=0),
        ),
    ]
